version: 1

input:
  dir: ../tests/fixtures/model_record/include
  clang_args:
    - -std=c++11
    - -x
    - c++
    - -I../tests/fixtures/model_record/include

output:
  dir: ./pkg/gen-model

naming:
  prefix: gen
  style: preserve
