version: 1

input:
  dir: ../tests/fixtures/isaamaster/includehttps://github.com/kyh0703/cgo-gen/pull/5/conflict?name=src%252Fcompiler.rs&ancestor_oid=da5b8fe21ee9b6239fd30ba42488a5355fe24b97&base_oid=d5aaa9f781d0cf22d5dcd42992638d46640a19a4&head_oid=30f37ab25929450461ef63c3fe3524b35d30ea45
  compile_commands: ../tests/fixtures/isaamaster/build/compile_commands.json
  clang_args:
    - -std=c++11
    - -x
    - c++
    - -I../tests/fixtures/isaamaster/include

output:
  dir: ./pkg/sil-real-model

naming:
  prefix: sil
  style: preserve

policies:
  string_mode: c_str
  enum_mode: c_enum
  unsupported:
    templates: error
    stl_containers: skip
    exceptions: error
